name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  GO_VERSION: "1.21"

jobs:
  build:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get version info
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')
          COMMIT=$(git rev-parse --short HEAD)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "build_time=$BUILD_TIME" >> $GITHUB_OUTPUT
          echo "commit=$COMMIT" >> $GITHUB_OUTPUT

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ steps.version.outputs.version }}
          BUILD_TIME: ${{ steps.version.outputs.build_time }}
          COMMIT: ${{ steps.version.outputs.commit }}
        run: |
          BINARY_NAME="base-linux-setup-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi

          go build -ldflags "-X main.version=${VERSION} -X main.buildTime=${BUILD_TIME} -X main.commit=${COMMIT}" -o ${BINARY_NAME} .

          # Create checksum
          sha256sum ${BINARY_NAME} > ${BINARY_NAME}.sha256

          echo "BINARY_NAME=${BINARY_NAME}" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            base-linux-setup-*
            *.sha256

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: binaries-*
          merge-multiple: true

      - name: Get version info
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          if [ $(git tag --list | wc -l) -gt 1 ]; then
            PREV_TAG=$(git tag --sort=-version:refname | sed -n '2p')
            echo "## What's Changed" > CHANGELOG.md
            git log --pretty=format:"- %s" ${PREV_TAG}..HEAD >> CHANGELOG.md
          else
            echo "## Initial Release" > CHANGELOG.md
            echo "First release of Base Linux Setup CLI tool." >> CHANGELOG.md
          fi

          echo "" >> CHANGELOG.md
          echo "## Installation" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "### Download and run directly:" >> CHANGELOG.md
          echo '```bash' >> CHANGELOG.md
          echo "# For Raspberry Pi 4+ (ARM64)" >> CHANGELOG.md
          echo "wget https://github.com/GuilhermeVozniak/base-linux-setup/releases/download/${{ steps.version.outputs.version }}/base-linux-setup-linux-arm64" >> CHANGELOG.md
          echo "chmod +x base-linux-setup-linux-arm64" >> CHANGELOG.md
          echo "./base-linux-setup-linux-arm64" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "# For standard Linux x86_64" >> CHANGELOG.md
          echo "wget https://github.com/GuilhermeVozniak/base-linux-setup/releases/download/${{ steps.version.outputs.version }}/base-linux-setup-linux-amd64" >> CHANGELOG.md
          echo "chmod +x base-linux-setup-linux-amd64" >> CHANGELOG.md
          echo "./base-linux-setup-linux-amd64" >> CHANGELOG.md
          echo '```' >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "### Verify checksums:" >> CHANGELOG.md
          echo '```bash' >> CHANGELOG.md
          echo "sha256sum -c base-linux-setup-linux-amd64.sha256" >> CHANGELOG.md
          echo '```' >> CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md
          files: |
            base-linux-setup-*
            *.sha256
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
